{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "myapp.serviceAccountName" . }}
  labels:
{{ include "myapp.labels" . | indent 4 }}
{{- end -}}
